# Generated by Django 5.1.3 on 2024-11-18 04:04

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_bookmark_options_remove_bookmark_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clap",
            old_name="clapped_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image (optional)",
                null=True,
                upload_to=projects.models.comment_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="additional_files",
            field=models.FileField(
                blank=True,
                help_text="Upload additional files (PDF, DOC, TXT, ZIP - max 10MB)",
                null=True,
                upload_to=projects.models.project_file_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "txt", "zip"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a featured image for your project",
                null=True,
                upload_to=projects.models.project_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF document (max 10MB)",
                null=True,
                upload_to=projects.models.project_file_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=projects.models.avatar_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(blank=True, max_length=39),
        ),
    ]
