# Generated by Django 5.1.3 on 2024-11-18 15:11

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_userprofile_email_on_bookmark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.URLValidator(),
                    projects.models.validate_github_url,
                ],
            ),
        ),
    ]
