# Generated by Django 5.1.3 on 2024-11-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_team_teamanalytics_teamdiscussion_teamcomment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammembership",
            options={},
        ),
        migrations.RenameField(
            model_name="teammembership",
            old_name="joined_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="teammembership",
            name="notification_preferences",
        ),
        migrations.AddField(
            model_name="teammembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("founder", "Founder"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=10,
            ),
        ),
    ]
