# Generated by Django 5.1.3 on 2024-11-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0030_application_additional_info_application_cover_letter_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="application",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="application",
            name="cover_letter",
        ),
        migrations.RemoveField(
            model_name="application",
            name="resume",
        ),
        migrations.AlterField(
            model_name="application",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="PDF format preferred, max 10MB",
                null=True,
                upload_to="applications/",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="message",
            field=models.TextField(
                help_text="Tell us about yourself or your organization"
            ),
        ),
    ]
