# Generated by Django 5.1.3 on 2024-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_alter_application_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KHCCBrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("total_comments", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "KHCC Brain",
                "verbose_name_plural": "KHCC Brain Instances",
            },
        ),
    ]
