# Generated by Django 5.1.3 on 2024-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_teammembership_receive_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_on_featured_seed",
            field=models.BooleanField(
                default=True, help_text="Email me when new featured seeds are posted"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_gold_seed",
            field=models.BooleanField(
                default=True, help_text="Email me when new gold seeds are posted"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_team_comment",
            field=models.BooleanField(
                default=True,
                help_text="Email me when someone comments on team discussions",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_team_discussion",
            field=models.BooleanField(
                default=True,
                help_text="Email me when there's a new discussion in my teams",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_bookmark",
            field=models.BooleanField(
                default=False, help_text="Email me when someone bookmarks my content"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_clap",
            field=models.BooleanField(
                default=False, help_text="Email me when someone claps for my content"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_comment",
            field=models.BooleanField(
                default=True, help_text="Email me when someone comments on my content"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_follow",
            field=models.BooleanField(
                default=True, help_text="Email me when someone follows me"
            ),
        ),
    ]
