# Generated by Django 5.1.3 on 2024-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_userprofile_email_on_featured_seed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_bookmark",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_clap",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_comment",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_follow",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_team_discussion",
            field=models.BooleanField(
                default=True, help_text="Email me when there's a new team discussion"
            ),
        ),
    ]
