# Generated by Django 5.1.3 on 2024-11-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_remove_userprofile_email_on_featured_seed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_on_featured_seed",
            field=models.BooleanField(
                default=True, help_text="Email me when a new featured seed is posted"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_gold_seed",
            field=models.BooleanField(
                default=True, help_text="Email me when a new gold seed is posted"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_team_comment",
            field=models.BooleanField(
                default=True,
                help_text="Email me when someone comments in my team discussions",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_team_discussion",
            field=models.BooleanField(
                default=True,
                help_text="Email me when someone posts a discussion in my teams",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_bookmark",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_clap",
            field=models.BooleanField(default=True),
        ),
    ]
