# Generated by Django 5.1.3 on 2024-11-17 22:18

import django.core.validators
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(
                validators=[
                    django.core.validators.URLValidator(),
                    projects.models.validate_github_url,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Enter tags separated by commas", max_length=100
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clap",
            unique_together={("project", "user")},
        ),
    ]
