# Generated by Django 5.1.3 on 2024-11-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_notification_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="notes",
        ),
    ]
