# Generated by Django 5.1.3 on 2024-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="total_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
