# Generated by Django 5.1.3 on 2024-11-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_project_total_ratings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="total_ratings",
            new_name="rating_count",
        ),
        migrations.AddField(
            model_name="project",
            name="rating_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
