# Generated by Django 5.1.3 on 2024-11-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_rename_total_ratings_project_rating_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="research_interests",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
