# Generated by Django 5.1.3 on 2024-11-18 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_userprofile_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="claps",
            new_name="clap_count",
        ),
        migrations.AlterField(
            model_name="clap",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claps",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="clap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_claps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
