# Generated by Django 5.1.3 on 2024-11-19 15:40

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_comment_clap_count_commentclap"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a YouTube video for your project",
                null=True,
                validators=[projects.models.validate_youtube_url],
            ),
        ),
    ]
