# Generated by Django 5.1.3 on 2024-11-19 17:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_alter_userprofile_talent_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_gold",
            field=models.BooleanField(
                default=False, help_text="Mark this as a Gold Seed (Faculty only)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reward_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All Complete"),
                    ("first", "First to Complete"),
                    ("best", "Best Solution"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="token_reward",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of tokens awarded for completion",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="solutions/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "zip",
                                    "py",
                                    "ipynb",
                                    "txt",
                                ]
                            )
                        ],
                    ),
                ),
                ("github_link", models.URLField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("faculty_feedback", models.TextField(blank=True)),
                ("tokens_awarded", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user")},
            },
        ),
    ]
