# Generated by Django 5.1.3 on 2024-11-19 19:45

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_alter_teammembership_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="team",
            name="max_members",
        ),
        migrations.AddField(
            model_name="team",
            name="team_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a team profile image",
                null=True,
                upload_to=projects.models.team_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
