# Generated by Django 5.1.3 on 2024-11-21 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_dataset_product_sponsorship_tool_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="resume",
            new_name="attachment",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="cover_letter",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="application",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="application",
            name="status",
        ),
        migrations.RemoveField(
            model_name="application",
            name="type",
        ),
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="organization",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
