# Generated by Django 5.1.3 on 2024-11-21 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_rename_resume_application_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="cover_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/cover_letters/"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/resumes/"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="type",
            field=models.CharField(
                choices=[("sponsor", "Sponsor"), ("team", "Team Member")],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/attachments/"
            ),
        ),
    ]
