# Generated by Django 5.1.3 on 2024-11-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_khccbrain"),
    ]

    operations = [
        migrations.AddField(
            model_name="khccbrain",
            name="description",
            field=models.CharField(
                default="AI Research Assistant & Team Mentor", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="khccbrain",
            name="name",
            field=models.CharField(default="KHCC Brain", max_length=50),
        ),
    ]
