# Generated by Django 5.1.3 on 2024-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_khccbrain_description_khccbrain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamdiscussion",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
