# Generated by Django 5.1.3 on 2024-11-22 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_teamdiscussion_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembership",
            name="receive_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("moderator", "Moderator"),
                    ("founder", "Founder"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
